name: default
root: ~/
windows:
      - system:
          layout: ebfc,188x53,0,0[188x36,0,0{94x36,0,0,4,93x36,95,0,8},188x16,0,37,7]
          panes:
            - screenfetch
            - ranger
            - htop
      - vim:
          layout: 8574,188x53,0,0[188x41,0,0,0,188x11,0,42{94x11,0,42,2,93x11,95,42,3}]
          panes: 
            - vim
            - clear
            - clear
      - music:
          layout: be7e,188x53,0,0,1
          panes:
            - ncmpcpp
